### ISSUE TITLE
json file or cache file error

### ISSUE THREAD

**Issue by matthewyccheung** [ran-xie/boosted-conformal#1]
Thanks for the excellent paper and codebase!
`len_local_boost` works great, but when I want to run `condconv_local_boost`, I get an error.
It seems like I need to get some .json cache files, but I am unsure.
Any thoughts on how to debug this?

```
Fatal error: cannot open file '.../boostedCP/contrast_trees_r.R': No such file or directory
Traceback (most recent call last):
  File "some_file.py", line 71, in <module>
    results_local = condcov_local_boost(X_train, y_train, X_cal, y_cal,X_test, y_test, 
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../boosted-conformal/boostedCP/condcov_local_boost.py", line 59, in condcov_local_boost
    cri_test=np.array(json_contrast_test["cri"])
                      ~~~~~~~~~~~~~~~~~~^^^^^^^
KeyError: 'cri'
```

Thanks!

**Comment by ran-xie** [comment]
Hello,

Thank you for reaching out!

It appears that the r script contrast_trees_r.R was not executed. Could you please verify the following:
1. You are running the figure3.py script (or your own script) within the experiments directory.
2. R is installed on your system. You can confirm this by running the command `which Rscript` in the terminal.
3. The necessary R packages listed in the README have been installed.
4. The directories cache/concrete have been manually created under the experiments folder.
If you encounter any further issues, please don’t hesitate to let me know.

Best,
Ran
